### ISSUE TITLE
'GPT2Config' object has no attribute 'shared_attention'

### ISSUE THREAD

**Issue by benjpau** [caoyu-noob/D3#2]
When I run train_gpt2.sh, I get this error：
```
Traceback (most recent call last):
  File "train.py", line 500, in <module>
    main()
  File "train.py", line 492, in main
    model, tokenizer = get_model_and_tokenizer(args, trainer_config, logger)
  File "train.py", line 105, in get_model_and_tokenizer
    model = GPT2DoubleHeadsModel.from_pretrained('/home/ma-user/work/baojianzhu/gpt2')
  File "/home/ma-user/anaconda3/envs/d3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 852, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/ma-user/work/baojianzhu/grounded/D3/model/gpt2_model.py", line 847, in __init__
    self.transformer = GPT2Model(config, sinlge_input=True)
  File "/home/ma-user/work/baojianzhu/grounded/D3/model/gpt2_model.py", line 500, in __init__
    self.h = nn.ModuleList([Block(config.n_ctx, config, scale=True, single_input=sinlge_input) for _ in range(config.n_layer)])
  File "/home/ma-user/work/baojianzhu/grounded/D3/model/gpt2_model.py", line 500, in <listcomp>
    self.h = nn.ModuleList([Block(config.n_ctx, config, scale=True, single_input=sinlge_input) for _ in range(config.n_layer)])
  File "/home/ma-user/work/baojianzhu/grounded/D3/model/gpt2_model.py", line 282, in __init__
    self.shared_attention = config.shared_attention
AttributeError: 'GPT2Config' object has no attribute 'shared_attention'
```

I checked the transformer version but didn't solve this issue. Could you give me some clues?

**Comment by caoyu-noob** [comment]
It should be the same problem as the former one. This repo is basically forked from https://github.com/caoyu-noob/Multi-GPT2 and it should use a specific config.json file I define in that repo.
I have updated `gpt2_model.py` and the raw config file from GPT2 should also be applicable.

**Comment by benjpau** [comment]
Thanks a lot!
